name: Build
on:
  pull_request:
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up Python
        id: py
        uses: actions/setup-python@v6
      - name: Install poetry
        run: pipx install --python '${{ steps.py.outputs.python-path }}' poetry
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: Build website
        run: poetry run mkdocs --color build --strict
